// =============================================================================
// apps.rs — Torchform app window manager
//
// Opens stub app windows (Settings, Files) from command-palette selections.
// Slint types (AppSettings, AppFiles) are generated at the crate root by
// the include_modules!() call in main.rs — no second include needed here.
// =============================================================================

use anyhow::Result;
use slint::ComponentHandle;
use tracing::info;

// Slint types live at the crate root (generated by include_modules!() in main.rs)
use crate::{AppSettings, AppFiles};

/// Maps a palette command-id to a launchable app.
pub fn launch_from_command(
    settings: &mut Option<AppSettings>,
    files:    &mut Option<AppFiles>,
    command_id: &str,
) -> Result<bool> {
    match command_id {
        "settings" | "open-settings" => {
            open_settings(settings)?;
            Ok(true)
        }
        "file-manager" | "open-files" => {
            open_files(files)?;
            Ok(true)
        }
        _ => Ok(false),
    }
}

pub fn open_settings(slot: &mut Option<AppSettings>) -> Result<()> {
    if slot.is_none() {
        let w = AppSettings::new()?;
        w.on_close_requested({
            let wk = w.as_weak();
            move || { wk.upgrade().map(|s| s.hide().ok()); }
        });
        *slot = Some(w);
    }
    slot.as_ref().unwrap().show()?;
    info!("Settings window shown");
    Ok(())
}

pub fn open_files(slot: &mut Option<AppFiles>) -> Result<()> {
    if slot.is_none() {
        let w = AppFiles::new()?;
        w.on_close_requested({
            let wk = w.as_weak();
            move || { wk.upgrade().map(|s| s.hide().ok()); }
        });
        w.on_navigate({
            let wk = w.as_weak();
            move |name| {
                if let Some(ww) = wk.upgrade() {
                    let cur: String = ww.get_current_path().to_string();
                    let new_path = format!("{cur}/{name}");
                    ww.set_current_path(new_path.into());
                    info!("Files: navigate → {}", ww.get_current_path());
                }
            }
        });
        *slot = Some(w);
    }
    slot.as_ref().unwrap().show()?;
    info!("Files window shown");
    Ok(())
}

/// Container held by ShellApp so windows survive across events.
pub struct AppManager {
    pub settings: Option<AppSettings>,
    pub files:    Option<AppFiles>,
}

impl AppManager {
    pub fn new() -> Self {
        Self { settings: None, files: None }
    }

    pub fn launch(&mut self, command_id: &str) -> Result<bool> {
        launch_from_command(&mut self.settings, &mut self.files, command_id)
    }
}
