// =============================================================================
// apps.rs — Torchform app window manager
//
// Opens stub app windows (Settings, Files) from command-palette selections.
// Slint types (AppSettings, AppFiles) are generated at the crate root by
// the include_modules!() call in main.rs — no second include needed here.
// =============================================================================

use anyhow::Result;
use slint::ComponentHandle;
use tracing::info;

// Slint types live at the crate root (generated by include_modules!() in main.rs)
use crate::{AppSettings, AppFiles};

/// Maps a palette command-id to a launchable app.
///
/// On the real DE (CM5 with compositor), external processes are spawned and
/// inherit `WAYLAND_DISPLAY` from the compositor. In the emulator / Docker,
/// the Slint stub windows are shown as a fallback.
///
/// To add a new app: add a new entry in `palette.rs::default_commands()`,
/// then match its id here. Use `std::process::Command::new("binary").spawn()`
/// for real apps; fall back to a Slint stub if the binary is not found.
pub fn launch_from_command(
    settings: &mut Option<AppSettings>,
    files:    &mut Option<AppFiles>,
    command_id: &str,
) -> Result<bool> {
    match command_id {
        "app.settings" | "settings" | "open-settings" => {
            // Prefer a native settings app on the real DE
            if std::process::Command::new("gnome-control-center").spawn().is_err() {
                open_settings(settings)?;
            }
            Ok(true)
        }
        "app.files" | "file-manager" | "open-files" => {
            // Thunar is the preferred file manager for the CM5 build.
            // Any Wayland-native file manager works; it connects to $WAYLAND_DISPLAY
            // set by torchform-compositor.  Falls back to the stub in emulator/Docker.
            if std::process::Command::new("thunar").spawn().is_err() {
                open_files(files)?;
            }
            Ok(true)
        }
        _ => Ok(false),
    }
}

pub fn open_settings(slot: &mut Option<AppSettings>) -> Result<()> {
    if slot.is_none() {
        let w = AppSettings::new()?;
        w.on_close_requested({
            let wk = w.as_weak();
            move || { wk.upgrade().map(|s| s.hide().ok()); }
        });
        *slot = Some(w);
    }
    slot.as_ref().unwrap().show()?;
    info!("Settings window shown");
    Ok(())
}

pub fn open_files(slot: &mut Option<AppFiles>) -> Result<()> {
    if slot.is_none() {
        let w = AppFiles::new()?;
        w.on_close_requested({
            let wk = w.as_weak();
            move || { wk.upgrade().map(|s| s.hide().ok()); }
        });
        w.on_navigate({
            let wk = w.as_weak();
            move |name| {
                if let Some(ww) = wk.upgrade() {
                    let cur: String = ww.get_current_path().to_string();
                    let new_path = format!("{cur}/{name}");
                    ww.set_current_path(new_path.into());
                    info!("Files: navigate → {}", ww.get_current_path());
                }
            }
        });
        *slot = Some(w);
    }
    slot.as_ref().unwrap().show()?;
    info!("Files window shown");
    Ok(())
}

/// Container held by ShellApp so windows survive across events.
pub struct AppManager {
    pub settings: Option<AppSettings>,
    pub files:    Option<AppFiles>,
}

impl AppManager {
    pub fn new() -> Self {
        Self { settings: None, files: None }
    }

    pub fn launch(&mut self, command_id: &str) -> Result<bool> {
        launch_from_command(&mut self.settings, &mut self.files, command_id)
    }
}
